#!/usr/bin/make -f
#
# This makefile needs GNU make.
#
TOPDIR=..

MODULES=\
	destroy.sh\
	final.sh\
	introspect.sh\
	prettyprint.sh\
	serialize.sh\
	thread.sh\
	use.sh\
	also_inherit.sh\
	www.sh\
	dns.sh\
	list.sh\
	stack.sh\
	onexit.sh\
	alist.sh\
	ref.sh\
	shoop.sh\
	shoop_command.sh\
	stringutil.sh\

include $(TOPDIR)/Makefile.vars
include $(TOPDIR)/Makefile.rules
