#!/usr/bin/make -f
#
# This makefile needs GNU make.
#

inst_msg = echo Installing $(msg) from $< to $$\(prefix\)$$\($(thisdir)\)/$<.
strip_comment_space = $(TOPDIR)/utils/shell-stripper
this_dir := $(patsubst $(shell cd $(TOPDIR); /bin/pwd)/%,%,$(CURDIR))

unexport clean_files clean_dirs
install:\
	installshowconfig\
	install.subdirs\
	installmodules.real\
	installbins.real\
	installdocs.real\
	installexamples.real\

$(patsubst %,install%.subdirs,modules bins docs examples dirs): %.subdirs:
ifdef SUBDIRS
	set -e;\
	for a in $(SUBDIRS); do\
		$(MAKE) -C $$a $*;\
	done
endif

$(patsubst %,install%,modules bins docs examples dirs): %: %.real %.subdirs

installmodules.real	: $(patsubst %, $(prefix)$(moddir)/%,$(MODULES))
installbins.real	: $(patsubst %, $(prefix)$(bindir)/%,$(BINS))
installdocs.real	: $(patsubst %, $(prefix)$(docdir)/%,$(DOCS))
installexamples.real	: $(patsubst %, $(prefix)$(empdir)/%,$(EXAMPLES))
installdirs.real	: $(patsubst %,$(prefix)%,$(DIRS))

installshowconfig:
ifdef VERBOSE
	echo "prefix is: $(prefix)"
	echo "bindir is: $(bindir)"
	echo "moddir is: $(moddir)"
	echo
endif

$(patsubst %, $(prefix)$(moddir)/%,$(MODULES))	: msg=$(MODULES_MSG)
$(patsubst %, $(prefix)$(bindir)/%,$(BINS))	: msg=$(BINS_MSG)
$(patsubst %, $(prefix)$(docdir)/%,$(DOCS))	: msg=$(DOCS_MSG)
$(patsubst %, $(prefix)$(empdir)/%,$(EXAMPLES))	: msg=$(EXAMPLES_MSG)
$(patsubst %, $(prefix)$(moddir)/%,$(MODULES))	: thisdir=moddir
$(patsubst %, $(prefix)$(bindir)/%,$(BINS))	: thisdir=bindir
$(patsubst %, $(prefix)$(docdir)/%,$(DOCS))	: thisdir=docdir
$(patsubst %, $(prefix)$(empdir)/%,$(EXAMPLES))	: thisdir=empdir

ifneq ($(MODULES),)
DIRS += $(moddir)
$(patsubst %, $(prefix)$(moddir)/%,$(MODULES)): $(prefix)$(moddir)/%: % $(prefix)$(moddir) $(strip_comment_space)
	$(inst_msg)
	$(strip_comment_space) < $< > $@
endif

ifneq ($(BINS),)
DIRS += $(bindir)
$(patsubst %, $(prefix)$(bindir)/%,$(BINS)): $(prefix)$(bindir)/%: % $(prefix)$(bindir) $(strip_comment_space)
	$(inst_msg)
	$(strip_comment_space) < $< > $@
	chmod +x $@
endif

ifneq ($(DOCS),)
DIRS += $(docdir)
$(patsubst %, $(prefix)$(docdir)/%,$(DOCS)): $(prefix)$(docdir)/%: % $(prefix)$(docdir)
	$(inst_msg)
	install -m 644 $< $@
endif

ifneq ($(EXAMPLES),)
DIRS += $(empdir)
$(patsubst %, $(prefix)$(empdir)/%,$(EXAMPLES)): $(prefix)$(empdir)/%: % $(prefix)$(empdir)
	$(inst_msg)
	install -m 644 $< $@
endif

$(patsubst %,$(prefix)%,$(sort $(DIRS))): $(prefix)%:
	echo Making dir $$\(prefix\)$*
	mkdir -p $@

.PHONY: installshowconfig installdirs installdocs installbins installshare ChangeLog

clean: clean.subdirs
	echo Cleaning in $(this_dir)
	if [ "$(clean_files)" ];then rm -f $(clean_files); fi
	if [ "$(clean_dirs)" ];then rm -rf $(clean_dirs); fi

modules_tmp: modules_tmp.subdirs
	modules="$(patsubst %,$(this_dir)/%,$(MODULES))";\
	if [ "$$modules" ]; then\
		echo $$modules;\
	fi >> $(TOPDIR)/$@


ifndef NOISY
.SILENT:
endif

include $(TOPDIR)/Makefile.vars
