#!/usr/bin/make -f
#
# This makefile needs GNU make.
#
.EXPORT_ALL_VARIABLES:
prefix=$(CURDIR)/debian/tmp

moddir=/usr/share/shoop/modules
bindir=/usr/bin
docdir=/usr/share/doc
mandir=/usr/share/man
empdir=$(docdir)/examples

MODULES_MSG=modules
BINS_MSG=binary
DOCS_MSG=documents
EXAMPLES_MSG=examples
MAN_MSG=man pages

PKG=shoop
PKG_VER=0.1

unexport BINS MODULES DOCS EXAMPLES MANPAGES SUBDIRS

