#!/bin/sh -e
NAMES=$(awk "
/^CVS:/{
	sub(/'/, \"'\\''\");
	sub(/^CVS:/, \"\");
	printf \"-u '%s:\", \$1;
	sub(\$1 \" \",\"\");
	split(\$0, A, / *[<>] */);
	printf \"%s:%s'\n\", A[1], A[2]
}
" docs/AUTHORS)
eval rcs2log -v $NAMES | 
awk '
/	\* /{
	split($0,A,/:/);
	count=split(A[1],B,/, /);
	first=1;
	for(C = 1; C <= count; C++) {
		if(!first)
			printf ", ";
		sub(/\/cvsroot\/shoop\/shoop\//,"",B[C]);
		printf "%s", B[C];
		first=0
	}
	printf ":%s\n", A[2];
	printed=1
}
{
	if(printed != 1)
		print;
	printed=0
}
' > ${1:-ChangeLog}
