#!/usr/bin/perl
#
# This is a perl script that can strip uneeded characters from a
# shell script, so that certain shells(bash!) can run it faster.
#
# Copyright 2000 by Adam Heath <doogie@debian.org>
# Licensed under the LGPL
#

## A semi-simple shell comment stripper
## 
## It was found that certain shell interpeters ran faster, if leading
## blank space was removed, along with comments.  This program was
## designed to remove text that match the above constraints.
## 
## Items removed
##>4
##:blank lines
##:leading white space
##:comment lines
##<
## Combined lines
##>4
##:\\
## A line ending with \\ has the \\ removed, and the next line is
## concatenated to the current line, before processing is continued.
##:;
## ; is a command delimiter, so it is safe to combined a command from
## subsequent lines onto the end of the current line.
##<
$first = 1;
while (<>) {

	#
	# Remove continuation characters.  This is done first
	# incase the script magic below is a continued line.
	#
	if(/\\$/) {
		chop;s/\\$//;
		$_ .= <>;
		redo if not eof;
	};

	#
	# Don't throw away the script magic identifier.
	#
	if(!(defined $first && /^#!/)) {
		#
		# Strip leading whitespace.
		#
		s/[ \t]*//;

		#
		# Skip blank and comment lines.
		#
		next if(/^(#.*|)$/);
	}

	#
	# If a line ends with ;, then combine it with the next
	# line, as the new line character is extraneous.
	#
	chop if(/\;[ \t]*$/);

	print if(/^#!/);
	if(defined $first) {
		print "# This script has been preprocessed prior to installation\n";
		print "# It has had comments, blank lines, and leading spaces\n";
		print "# removed, and \\-style lines combined.  This was done so\n";
		print "# that it could run quicker under some shells.\n"
	}
	print if(! /^#!/);
	undef $first;

}
