#!/bin/sh
# Regression test framework (modeled on perl's if you can't tell).

set -e
TMPF1=$(mktemp $(/bin/pwd)/regress.XXXXXX)
TMPF2=$(mktemp $(/bin/pwd)/regress.XXXXXX)
trap 'rm -rf $TMPF1 $TMPF2' 0

# Call this function to test something.
ok () {
	local name expected_return="$2" expected_output="$3" ret output
	testcount=$(($testcount + 1))
	if [ "x$1" != "x" ]; then
		name="$1($testcount)"
	else
		name=$testcount
	fi
	shift 3
	rm -f $TMPF1 $TMPF2	
	set +e
	"$@" > $TMPF1
	ret=$?
	set -e
	bad=0
	if [ "$expected_return" != "$ret" ]; then
		echo "say \"test $name FAILED: expected return code $expected_return, but got $ret\""
		bad=1
	fi
	output="$(< $TMPF1)"
	if [ ${#output} -eq ${#expected_output} ]; then
		if [ "z$output" != "z$expected_output" ]; then
			echo "say \"test $name FAILED: expected \\\`$expected_output', but got \\\`$output'\""
			bad=1
		fi
	else
		if [ $(wc -c < $TMPF1) -gt 0 ]; then
			echo >> $TMPF1
		fi
		if [ ${#expected_output} -gt 0 ]; then
			echo "$expected_output" > $TMPF2
		else
			: > $TMPF2
		fi
		if ! diff -q $TMPF1 $TMPF2 1>/dev/null; then
			echo "say \"test $name FAILED: expected \\\`$expected_output', but got \\\`$(cat $TMPF1)'\""
			bad=1
		fi
	fi

	if [ $bad = 0 ]; then
		if [ "$VERBOSE" ]; then
			say "\"test $name succeeded\""
		fi
	else
		testfailures=$(($testfailures + 1))
	fi
}

# Call this function last say how many tests you should have run.
tests () {
	echo expected=$1
	echo testcount=$testcount
}

say () {
	if [ -z "$spoke" ]; then
		spoke=1
		echo
	fi
	echo "	$@"
}

totaltestcount=0
totalfailures=0

if [ "$1" ]; then
	for script in "$@"; do
		# This part runs a regression test script (which uses the code above),
		# and parses the output to print a human-readable summary.
			
		spoke=""
		echo -n Beginning test of $script ..
		testcount=0
		testfailures=0
		eval "$(. $script || echo woah)"
		if [ "$expected" -a "$expected" != "$testcount" ]; then
			say "($expected tests were expected, but $testcount were run)"
		fi
		if [ "$testfailures" != 0 ]; then
			echo ".. $testfailures test(s)(of $expected) FAILED."
		else
			if [ "$spoke" ]; then
				echo -n ".."
			fi		
			echo " all test(s) successful."
		fi

		totalfailures=$(($totalfailures + $testfailures)) || true
		totaltestcount=$(($totaltestcount + $testcount)) || true
	done
	echo
	echo "Regression test summary:"
	echo "	A total of $totaltestcount individual tests were ran,"
	echo -n "	from $(($#)) regression test scripts. "
	if [ "$totalfailures" != 0 ]; then
		echo "Of those, $totalfailures tests FAILED."
		exit 1
	else
		echo "All succeeded."
	fi
fi
